module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  autologout: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  bricks: 0
  bricks_inline: 0
  bricks_revisions: 0
  ckeditor: 0
  color: 0
  config: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dev_helper: 0
  devel: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  kint: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  media: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  password_policy: 0
  path: 0
  picture_background_formatter: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  settings_tray: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  tombras_extras: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  twig_xdebug: 0
  update: 0
  url_embed: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ui: 0
  viewsreference: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  tombras_profile: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  agnian_material_admin: 0
  tombras: 0
profile: tombras_profile
