dev_helper:
  recommended_modules:
    - address
    - admin_toolbar
    - adminimal_admin_toolbar
    - better_exposed_filters
    - devel
    - crop
    - media_entity
    - entity
    - entity_print
    - entity_browser
    - entity_browser_enhanced
    - entity_reference_revisions
    - extlink
    - editor_advanced_link
    - field_group
    - image_widget_crop
    - twig_field_value
    - inline_entity_form
    - twig_tweak
    - link_attributes
    - linkit
    - linked_field
    - link_class
    - maxlength
    - media_entity_document
    - media_entity_image
    - metatag
    - module_filter
    - rabbit_hole
    - redirect
    - search_api_page
    - sitemap
    - tablefield
    - video_embed_field
    - xmlsitemap
